# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Main test
on:
 push:
   branches:
     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # - name: Install dependencies
      #   run: python -m pip install --upgrade pip yq

      # - name: Main
      #   id: main
      #   env:
      #     OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
      #   run: |
      #     echo "PR labels : $OP_TEST_LABELS"
      #     echo "repo name: ${{ github.event.pull_request.head.repo.full_name }}"
      #     yq --version
      #     yq --version || { echo "Command 'yq' could not be found !!!"; exit 1; } 
      # - name: Operator traffic light
      #   id: op-traffic-light
      #   run: |
      #     echo "::set-output name=op_test_stream::upstream-community-operators"
      #     echo "::set-output name=op_test_name::aqua"
      #     exit 2
      # - name: Is aqua
      #   if: always() && steps.op-traffic-light.outputs.op_test_name == 'aqua'
      #   run: |
      #     echo "Aqua"
      # - name: Is not aqua
      #   if: always() && steps.op-traffic-light.outputs.op_test_name != 'aqua'
      #   run: |
      #     echo "Not Aqua"
