name: Main test
on:
 push:
   branches:
     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install --upgrade pip yq

      - name:
        run: |
          ansible-pull -U https://github.com/redhat-openshift-ecosystem/operator-test-playbooks -C upstream-community -i localhost, -e run_upstream=true -e run_prepare_catalog_repo_upstream=true upstream/local.yml --tags reset_tools,operator_info -e operator_dir=/tmp/community-operators-for-catalog/operators/elastic-cloud-eck -e cluster_type=k8s -e strict_cluster_version_labels=true -e strict_k8s_bundles=true -e production_registry_namespace=quay.io/operatorhubio -e automatic_cluster_version_label=false -e catalog_repo=https://github.com/naemono/community-operators -e catalog_repo_branch=2.2.0
      
      # - name: Main
      #   id: main
      #   env:
      #     OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
      #   run: |
      #     echo "PR labels : $OP_TEST_LABELS"
      #     echo "repo name: ${{ github.event.pull_request.head.repo.full_name }}"
      #     yq --version
      #     yq --version || { echo "Command 'yq' could not be found !!!"; exit 1; } 
      # - name: Operator traffic light
      #   id: op-traffic-light
      #   run: |
      #     echo "::set-output name=op_test_stream::upstream-community-operators"
      #     echo "::set-output name=op_test_name::aqua"
      #     exit 2
      # - name: Is aqua
      #   if: always() && steps.op-traffic-light.outputs.op_test_name == 'aqua'
      #   run: |
      #     echo "Aqua"
      # - name: Is not aqua
      #   if: always() && steps.op-traffic-light.outputs.op_test_name != 'aqua'
      #   run: |
      #     echo "Not Aqua"
