# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: PR target
on:
 pull_request_review:
   types: [submitted,edited]
   
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Author
        id: author
        run: |
          echo "github.event.issue.user.login: ${{ github.event.issue.user.login }}"
          echo "github.event.pull_request.user.login: ${{ github.event.pull_request.user.login }}"
          echo "github.event.pull_request.state: ${{ github.event.pull_request.state }}"
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event.review.state: ${{ github.event.review.state }}"
          echo "github.event.review.user.login: ${{ github.event.review.user.login }}"
          ls -al
      