# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: PR
on:
 pull_request:
   types: [opened, synchronize, reopened, ready_for_review]
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Test
      #   id: test
      #   env:
      #     OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
      #   run: |
      #     echo "PR labels : $OP_TEST_LABELS"
      #     echo "repo name: ${{ github.event.pull_request.head.repo.full_name }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator traffic light
        id: op-traffic-light
        run: |
          # git clone https://github.com/operator-framework/community-operators.git
          echo "::set-output name=op_test_stream::upstream-community-operators"
          echo "::set-output name=op_test_name::aqua"
          echo "OP_PR=${{ github.event.pull_request.number }}"
          

